version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test-pass
      POSTGRES_USER: test-user
      POSTGRES_DB: amigos
    ports:
      - 5432:5432
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge
